#!/usr/bin/env node
/**
 * Bump app version (e.g. 1.0.0 → 1.0.1).
 * Updates: app.config.ts (ios/ is generated by prebuild)
 * Run before building when releasing a new version.
 * Usage: node scripts/bump-version.js [patch|minor|major]
 * Default: patch (1.0.0 → 1.0.1)
 */

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const APP_CONFIG = path.join(ROOT, "app.config.ts");

const bump = process.argv[2] || "patch"; // patch | minor | major

function getCurrentVersion() {
  const config = fs.readFileSync(APP_CONFIG, "utf8");
  const m = config.match(/version:\s*["']([\d.]+)["']/);
  return m ? m[1] : "1.0.0";
}

function parseVersion(v) {
  const [major = 0, minor = 0, patch = 0] = v.split(".").map(Number);
  return { major, minor, patch };
}

function bumpVersion(v, type) {
  const { major, minor, patch } = parseVersion(v);
  if (type === "major") return `${major + 1}.0.0`;
  if (type === "minor") return `${major}.${minor + 1}.0`;
  return `${major}.${minor}.${patch + 1}`;
}

function setVersion(newVersion) {
  let config = fs.readFileSync(APP_CONFIG, "utf8");
  config = config.replace(/version:\s*["'][\d.]+["']/, `version: "${newVersion}"`);
  fs.writeFileSync(APP_CONFIG, config);
  console.log(`✓ Version bumped to ${newVersion}`);
}

const current = getCurrentVersion();
const next = bumpVersion(current, bump);
setVersion(next);
